// @ts-check
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { build, stripModuleSyntax } from '../scripts/build.js';

/** @type {string[]} */
const dirs = [];

async function tempDir() {
  const dir = await mkdtemp(path.join(tmpdir(), 'winamp-build-'));
  dirs.push(dir);
  return dir;
}

afterEach(async () => {
  await Promise.all(dirs.splice(0).map((dir) => rm(dir, { recursive: true, force: true })));
});

describe('stripModuleSyntax', () => {
  it('drops import lines and unwraps exports', () => {
    const source = [
      "import { a } from './a.js';",
      "import './side-effect.js';",
      'export function f() {}',
      '  export const x = 1;',
      'const keep = "import me";',
    ].join('\n');

    expect(stripModuleSyntax(source)).toBe(
      ['function f() {}', '  const x = 1;', 'const keep = "import me";'].join('\n'),
    );
  });
});

describe('build', () => {
  it('wraps the modules in one IIFE in the fixed order, skipping missing ones', async () => {
    const src = await tempDir();
    const out = path.join(src, 'theme.js');
    await writeFile(path.join(src, 'index.js'), "import { formatTime } from './time.js';\nmain();");
    await writeFile(path.join(src, 'time.js'), 'export function formatTime() {}');

    const output = await build({ srcDir: src, outFile: out });

    expect(output.startsWith('// generated by scripts/build.js')).toBe(true);
    expect(output).toContain('(function () {');
    expect(output.trimEnd().endsWith('})();')).toBe(true);
    expect(output).not.toMatch(/^\s*import\s/m);
    expect(output).not.toMatch(/^\s*export\s/m);
    expect(output.indexOf('// --- time.js ---')).toBeLessThan(output.indexOf('// --- index.js ---'));
    expect(output).not.toContain('marquee.js');
    expect(await readFile(out, 'utf8')).toBe(output);
  });

  it('fails when src/ has a file that is not in ORDER', async () => {
    const src = await tempDir();
    await writeFile(path.join(src, 'index.js'), 'main();');
    await writeFile(path.join(src, 'stray.js'), 'export const x = 1;');

    await expect(build({ srcDir: src, outFile: path.join(src, 'theme.js') })).rejects.toThrow('stray.js');
  });
});
