import js from '@eslint/js';
import globals from 'globals';

export default [
  {
    // theme.js is generated by scripts/build.js; lint the sources instead.
    ignores: ['theme.js', 'node_modules/**', 'coverage/**'],
  },
  js.configs.recommended,
  {
    files: ['src/**/*.js'],
    languageOptions: {
      sourceType: 'module',
      globals: { ...globals.browser, Spicetify: 'readonly' },
    },
  },
  {
    files: ['scripts/**/*.js', 'test/**/*.js', '*.config.js', 'eslint.config.mjs'],
    languageOptions: {
      sourceType: 'module',
      globals: { ...globals.node, ...globals.browser },
    },
  },
];
