// generated by scripts/build.js, do not edit
(function () {
'use strict';

// --- time.js ---
// @ts-check
// Time formatting for the display. Pure, no DOM.

/** @param {number} n */
const pad = (n) => String(n).padStart(2, '0');

/**
 * `m:ss`, or `h:mm:ss` past one hour. Anything that is not a non-negative
 * finite number reads as `0:00`, so a missing duration never breaks the text.
 * @param {unknown} ms
 * @returns {string}
 */
function formatTime(ms) {
  if (typeof ms !== 'number' || !Number.isFinite(ms) || ms < 0) return '0:00';
  const total = Math.floor(ms / 1000);
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  return h > 0 ? `${h}:${pad(m)}:${pad(s)}` : `${m}:${pad(s)}`;
}

// --- marquee.js ---
// @ts-check
// Text of the display and the scroll step. Pure, no DOM: the DOM side that
// measures the display and drives the timer lives in marquee-dom.js.

// Winamp put this between the end of the text and its next lap.
const SEPARATOR = '  ***  ';

/**
 * @typedef {object} Track
 * @property {string} artist
 * @property {string} title
 * @property {number} durationMs
 */

/**
 * Reduces Spicetify's player item to what the display needs. Every read is
 * optional so a missing item, a podcast without artists or a local file
 * without metadata still yields something to show.
 * @param {Partial<Spicetify.PlayerTrack> | undefined | null} item
 * @returns {Track}
 */
function describeItem(item) {
  const artists = item?.artists?.map((artist) => artist.name).filter(Boolean) ?? [];
  return {
    artist: artists.length > 0 ? artists.join(', ') : (item?.metadata?.artist_name ?? ''),
    title: item?.name ?? item?.metadata?.title ?? '',
    durationMs: item?.duration?.milliseconds ?? 0,
  };
}

/**
 * `ARTIST - TITLE (m:ss)`, uppercase. Without an artist only the title; with
 * nothing at all, the word WINAMP, which is what an idle Winamp showed.
 * @param {Track} track
 * @returns {string}
 */
function displayText({ artist, title, durationMs }) {
  const a = artist.trim();
  const t = title.trim();
  const base = a && t ? `${a} - ${t}` : t || a || 'WINAMP';
  const time = durationMs > 0 ? ` (${formatTime(durationMs)})` : '';
  return `${base}${time}`.toUpperCase();
}

/**
 * The window of `width` characters visible at `offset`, and the offset for
 * the next step. Text that fits is returned whole with the offset pinned at
 * zero; text that does not fit scrolls through `text + SEPARATOR` and wraps.
 * @param {string} text
 * @param {number} offset
 * @param {number} width
 * @returns {{ view: string, offset: number }}
 */
function scrollStep(text, offset, width) {
  if (width <= 0) return { view: '', offset: 0 };
  if (text.length <= width) return { view: text, offset: 0 };
  const loop = text + SEPARATOR;
  const start = offset % loop.length;
  return { view: (loop + loop).slice(start, start + width), offset: (start + 1) % loop.length };
}

// --- spectrum.js ---
// @ts-check
// State of the spectrum analyser. Pure, no DOM: drawing and scheduling live
// in spectrum-dom.js. Values are 0..1 fractions of the full bar height.

// 3 px bars with 1 px gaps in a 76 px canvas, the geometry of Winamp's own
// analyser (19 bands in 75 px).
const BARS = 19;
// Rows of 1 px in the 16 px canvas; the colour bands are counted in rows.
const ROWS = 16;
// How much a bar drops per frame when its target is lower.
const DECAY = 0.06;
// Weight of the previous target when a new random target comes in.
const SMOOTHING = 0.7;
// Frames a peak waits above a lower bar before it starts to fall.
const PEAK_HOLD = 15;
// How much a peak drops per frame once the hold is over.
const PEAK_FALL = 0.02;

const BANDS = /** @type {const} */ (['green', 'yellow', 'orange', 'red']);

/**
 * @typedef {typeof BANDS[number]} Band
 * @typedef {{ values: number[], targets: number[], peaks: number[], holds: number[] }} SpectrumState
 */

/**
 * @param {number} [bars]
 * @returns {SpectrumState}
 */
function createState(bars = BARS) {
  const zeros = () => new Array(bars).fill(0);
  return { values: zeros(), targets: zeros(), peaks: zeros(), holds: zeros() };
}

/**
 * Advances every bar by one frame, in place. While playing each bar chases a
 * smoothed random target, jumping up at once and falling at a fixed rate;
 * paused, the target is zero and everything decays. The peak rides on the
 * bar, holds for PEAK_HOLD frames once the bar drops under it, then falls.
 * @param {SpectrumState} state
 * @param {() => number} rng returns 0..1
 * @param {boolean} playing
 * @returns {SpectrumState}
 */
function nextFrame(state, rng, playing) {
  const { values, targets, peaks, holds } = state;
  for (let i = 0; i < values.length; i += 1) {
    const target = playing ? SMOOTHING * (targets[i] ?? 0) + (1 - SMOOTHING) * rng() : 0;
    targets[i] = target;
    const value = values[i] ?? 0;
    values[i] = target > value ? target : Math.max(0, value - DECAY);

    const current = values[i] ?? 0;
    const peak = peaks[i] ?? 0;
    if (current >= peak) {
      peaks[i] = current;
      holds[i] = PEAK_HOLD;
    } else if ((holds[i] ?? 0) > 0) {
      holds[i] = (holds[i] ?? 0) - 1;
    } else {
      peaks[i] = Math.max(0, peak - PEAK_FALL);
    }
  }
  return state;
}

/**
 * Colour band of a row counted from the bottom: the lowest quarter green,
 * then yellow, orange and red at the top.
 * @param {number} row
 * @param {number} totalRows
 * @returns {Band}
 */
function colorForRow(row, totalRows) {
  const band = Math.min(3, Math.max(0, Math.floor((row / totalRows) * 4)));
  return BANDS[band] ?? 'green';
}

/**
 * True when nothing is left to animate: every bar and every peak at zero.
 * @param {SpectrumState} state
 * @returns {boolean}
 */
function isIdle(state) {
  return state.values.every((v) => v === 0) && state.peaks.every((p) => p === 0);
}

// --- dom.js ---
// @ts-check
// The one module that touches the DOM and the Spicetify globals. The other
// modules in src/ stay pure so they can be tested without a browser.
//
// An injection is a small feature (marquee, spectrum, title bar) that mounts
// into the display of the now playing bar. Each one runs in isolation: a
// throw is logged with the theme prefix and the next injection still runs.

/**
 * @typedef {object} Injection
 * @property {string} name
 * @property {(display: HTMLElement) => void} run
 * @property {(display: HTMLElement) => void} [cleanup]
 */

const LOG_PREFIX = '[winamp-classic]';

// The display is the track info block that user.css turns into the LED
// panel. It only exists while something is playing.
const DISPLAY_SELECTOR = '.main-nowPlayingBar-nowPlayingBar [data-testid="now-playing-widget"]';

// The stable parent of the bar. Spotify remounts the bar inside it in some
// flows, so this is what the observer watches.
const BAR_SELECTOR = '[data-testid="now-playing-bar"]';

/** @returns {boolean} */
function isSpicetifyReady() {
  return typeof Spicetify !== 'undefined' && Boolean(Spicetify.Player) && Boolean(Spicetify.Platform);
}

/**
 * Resolves once `isReady` reports true, polling on a timer. Rejects after
 * `timeoutMs` so a broken Spicetify never leaves the poll running forever.
 * @param {{ isReady?: () => boolean, intervalMs?: number, timeoutMs?: number }} [options]
 * @returns {Promise<void>}
 */
function waitForSpicetify({ isReady = isSpicetifyReady, intervalMs = 100, timeoutMs = 30000 } = {}) {
  return new Promise((resolve, reject) => {
    const started = Date.now();
    const poll = () => {
      if (isReady()) {
        resolve();
        return;
      }
      if (Date.now() - started >= timeoutMs) {
        reject(new Error(`Spicetify not ready after ${Math.round(timeoutMs / 1000)}s`));
        return;
      }
      setTimeout(poll, intervalMs);
    };
    poll();
  });
}

/**
 * @param {ParentNode} [root]
 * @returns {HTMLElement | null}
 */
function findDisplay(root = document) {
  return root.querySelector(DISPLAY_SELECTOR);
}

/**
 * Runs every injection against the display. Returns the ones whose `run` did
 * not throw, which is the set that later needs a cleanup.
 * @param {Injection[]} injections
 * @param {HTMLElement} display
 * @returns {Injection[]}
 */
function runInjections(injections, display) {
  return injections.filter((injection) => {
    try {
      injection.run(display);
      return true;
    } catch (err) {
      console.warn(`${LOG_PREFIX} ${injection.name}:`, err);
      return false;
    }
  });
}

/**
 * @param {Injection[]} injections
 * @param {HTMLElement} display
 */
function cleanupInjections(injections, display) {
  for (const injection of injections) {
    try {
      injection.cleanup?.(display);
    } catch (err) {
      console.warn(`${LOG_PREFIX} ${injection.name} cleanup:`, err);
    }
  }
}

/**
 * Mounts the injections into the display and keeps them mounted: a
 * MutationObserver on the bar re-runs them whenever the display element is
 * replaced, appears or goes away. Cleanup always runs before a new round, so
 * nothing gets duplicated.
 * @param {Injection[]} injections
 * @param {{ root?: Document }} [options]
 * @returns {{ remount: () => void, disconnect: () => void }}
 */
function mount(injections, { root = document } = {}) {
  /** @type {HTMLElement | null} */
  let display = null;
  /** @type {Injection[]} */
  let mounted = [];

  const sync = () => {
    const next = findDisplay(root);
    if (next === display) return;
    if (display) cleanupInjections(mounted, display);
    display = next;
    mounted = display ? runInjections(injections, display) : [];
  };

  const bar = root.querySelector(BAR_SELECTOR);
  const observer = new MutationObserver(sync);
  observer.observe(bar ?? root.body, { childList: true, subtree: true });

  sync();
  if (!display) console.warn(`${LOG_PREFIX} display not found, waiting for it`);

  return { remount: sync, disconnect: () => observer.disconnect() };
}

// --- marquee-dom.js ---
// @ts-check
// The DOM side of the marquee: a canvas next to Spotify's track info that
// shows the display text and scrolls it when it does not fit. user.css hides
// the track info while this element is present, so nothing React renders is
// ever touched and a remount is safe. Painting with fillText costs no layout,
// unlike rewriting a DOM text node five times a second.

const MARQUEE_CLASS = 'wa-marquee';
const TICK_MS = 200;
const DATA_POLL_MS = 250;
const TRACK_INFO_SELECTOR = '.main-nowPlayingWidget-trackInfo';

/**
 * Width in pixels of `text` in the element's computed font. Silkscreen is
 * proportional, so this is the honest measure; the character count of the
 * visible window comes from the average width of the text being shown.
 * @param {HTMLElement} el
 * @param {string} text
 * @returns {number}
 */
function canvasMeasure(el, text) {
  const ctx = document.createElement('canvas').getContext('2d');
  if (!ctx) return text.length * 8;
  ctx.font = getComputedStyle(el).font;
  return ctx.measureText(text).width;
}

/**
 * Paints the visible window. Font and colour are read once per layout, not
 * per tick, so the timer never forces style recalculation.
 * @param {Pick<CanvasRenderingContext2D, 'clearRect' | 'fillText' | 'font' | 'fillStyle' | 'textBaseline'>} ctx
 * @param {number} w
 * @param {number} h
 * @param {string} font
 * @param {string} color
 * @param {string} view
 */
function paintMarquee(ctx, w, h, font, color, view) {
  ctx.clearRect(0, 0, w, h);
  ctx.font = font;
  ctx.fillStyle = color;
  ctx.textBaseline = 'top';
  ctx.fillText(view, 0, 0);
}

/**
 * The slice of Spicetify.Player the marquee uses, so tests can pass a fake.
 * @typedef {object} PlayerLike
 * @property {Partial<Spicetify.PlayerState>} [data]
 * @property {(type: string, callback: () => void) => void} addEventListener
 * @property {(type: string, callback: () => void) => void} removeEventListener
 */

/**
 * @param {{ measure?: (el: HTMLElement, text: string) => number, player?: () => PlayerLike }} [options]
 * @returns {import('./dom.js').Injection}
 */
function createMarqueeInjection({ measure = canvasMeasure, player = () => Spicetify.Player } = {}) {
  /** @type {HTMLCanvasElement | null} */
  let el = null;
  /** @type {CanvasRenderingContext2D | null} */
  let ctx = null;
  /** @type {ReturnType<typeof setInterval> | null} */
  let timer = null;
  /** @type {ReturnType<typeof setInterval> | null} */
  let pending = null;
  /** @type {ResizeObserver | null} */
  let resize = null;
  let text = '';
  let offset = 0;
  let width = 0;
  let font = '';
  let color = '';

  const stop = () => {
    if (timer !== null) clearInterval(timer);
    timer = null;
  };

  /** @param {string} view */
  const paint = (view) => {
    if (ctx && el) paintMarquee(ctx, el.width, el.height, font, color, view);
  };

  const tick = () => {
    const step = scrollStep(text, offset, width);
    offset = step.offset;
    paint(step.view);
  };

  // Decides between static text and scrolling from the element's current
  // size. Called on mount, on every song change and when the display resizes.
  // The backing store follows the CSS box times the device pixel ratio, and
  // setTransform (not scale) resets the transform on every resize.
  const layout = () => {
    stop();
    if (!el || !ctx) return;
    const dpr = globalThis.devicePixelRatio || 1;
    el.width = Math.max(0, Math.round(el.clientWidth * dpr));
    el.height = Math.max(0, Math.round(el.clientHeight * dpr));
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    const style = getComputedStyle(el);
    font = style.font;
    color = style.color;
    const px = el.clientWidth;
    const needed = measure(el, text);
    // A zero width means the element is not laid out (hidden display, or a
    // test without layout): show the text whole and keep the timer off.
    if (px <= 0 || needed <= px) {
      paint(text);
      return;
    }
    width = Math.max(1, Math.floor(px / (needed / text.length)));
    tick();
    timer = setInterval(tick, TICK_MS);
  };

  const refresh = () => {
    text = displayText(describeItem(player().data?.item));
    offset = 0;
    el?.setAttribute('aria-label', text);
    layout();
  };

  // Spicetify fills Player.data a moment after the bar renders and fires
  // songchange only when the track uri changes, so a mount that lands before
  // the data would show WINAMP until the next track. Poll until it is there.
  const waitForData = () => {
    if (pending !== null) clearInterval(pending);
    pending = setInterval(() => {
      if (!player().data?.item) return;
      if (pending !== null) clearInterval(pending);
      pending = null;
      refresh();
    }, DATA_POLL_MS);
  };

  return {
    name: 'marquee',
    run(display) {
      el = document.createElement('canvas');
      el.className = MARQUEE_CLASS;
      const context = el.getContext('2d');
      if (!context) {
        console.warn(`${LOG_PREFIX} marquee: no 2d context, giving up`);
        el = null;
        return;
      }
      ctx = context;
      const info = display.querySelector(TRACK_INFO_SELECTOR);
      if (info) info.insertAdjacentElement('afterend', el);
      else display.append(el);
      refresh();
      if (!player().data?.item) waitForData();
      player().addEventListener('songchange', refresh);
      if (typeof ResizeObserver !== 'undefined') {
        resize = new ResizeObserver(layout);
        resize.observe(display);
      }
    },
    cleanup() {
      stop();
      if (pending !== null) clearInterval(pending);
      pending = null;
      resize?.disconnect();
      resize = null;
      try {
        player().removeEventListener('songchange', refresh);
      } catch (err) {
        console.warn(`${LOG_PREFIX} marquee: could not remove the songchange listener`, err);
      }
      el?.remove();
      el = null;
      ctx = null;
    },
  };
}

// --- spectrum-dom.js ---
// @ts-check
// The DOM side of the spectrum analyser: a canvas in the right padding of the
// display, drawn on requestAnimationFrame only while there is something to
// animate. Paused, the bars decay to zero and the loop stops on its own.

const SPECTRUM_CLASS = 'wa-spectrum';
const CANVAS_W = 76;
const CANVAS_H = 16;
const BAR_W = 3;
const GAP = 1;
// Below this display width the canvas would sit on top of the text.
const MIN_DISPLAY_W = 200;

// Theme token per band, with the scheme's own value as the fallback when the
// token cannot be read (a detached canvas, or a test without the stylesheet).
const COLOR_TOKENS = /** @type {const} */ ({
  green: ['--spice-text', '#00ff00'],
  yellow: ['--wa-vol-mid', '#ffff00'],
  orange: ['--spice-misc', '#ff9900'],
  red: ['--spice-notification-error', '#c60000'],
  peak: ['--wa-bevel-light', '#5a5a6e'],
});

/** @typedef {Record<keyof typeof COLOR_TOKENS, string>} Colors */

/**
 * @param {HTMLElement} el
 * @returns {Colors}
 */
function readColors(el) {
  const style = getComputedStyle(el);
  const entries = Object.entries(COLOR_TOKENS).map(([band, [token, fallback]]) => {
    return [band, style.getPropertyValue(token).trim() || fallback];
  });
  return /** @type {Colors} */ (Object.fromEntries(entries));
}

/**
 * Paints one frame: per bar, one 1 px row per unit of height in the colour of
 * its band, and the peak as a single row above.
 * @param {Pick<CanvasRenderingContext2D, 'clearRect' | 'fillRect' | 'fillStyle'>} ctx
 * @param {import('./spectrum.js').SpectrumState} state
 * @param {Colors} colors
 */
function drawFrame(ctx, state, colors) {
  ctx.clearRect(0, 0, CANVAS_W, CANVAS_H);
  for (let i = 0; i < state.values.length; i += 1) {
    const x = i * (BAR_W + GAP);
    const rows = Math.round((state.values[i] ?? 0) * ROWS);
    for (let row = 0; row < rows; row += 1) {
      ctx.fillStyle = colors[colorForRow(row, ROWS)];
      ctx.fillRect(x, CANVAS_H - 1 - row, BAR_W, 1);
    }
    const peakRow = Math.round((state.peaks[i] ?? 0) * ROWS) - 1;
    if (peakRow >= 0) {
      ctx.fillStyle = colors.peak;
      ctx.fillRect(x, CANVAS_H - 1 - peakRow, BAR_W, 1);
    }
  }
}

/**
 * The slice of Spicetify.Player the analyser uses, so tests can pass a fake.
 * @typedef {object} PlayerLike
 * @property {() => boolean} isPlaying
 * @property {(type: string, callback: () => void) => void} addEventListener
 * @property {(type: string, callback: () => void) => void} removeEventListener
 */

/**
 * @param {{
 *   rng?: () => number,
 *   player?: () => PlayerLike,
 *   schedule?: (callback: () => void) => number,
 *   cancel?: (id: number) => void,
 * }} [options]
 * @returns {import('./dom.js').Injection}
 */
function createSpectrumInjection({
  rng = Math.random,
  player = () => Spicetify.Player,
  schedule = (callback) => requestAnimationFrame(callback),
  cancel = (id) => cancelAnimationFrame(id),
} = {}) {
  /** @type {HTMLCanvasElement | null} */
  let canvas = null;
  /** @type {CanvasRenderingContext2D | null} */
  let ctx = null;
  /** @type {ResizeObserver | null} */
  let resize = null;
  /** @type {number | null} */
  let pending = null;
  let state = createState();
  /** @type {Colors | null} */
  let colors = null;

  // origin._state sits behind a getter that can be undefined for a moment.
  const playing = () => {
    try {
      return player().isPlaying();
    } catch {
      return false;
    }
  };

  const frame = () => {
    pending = null;
    if (!ctx || !colors) return;
    nextFrame(state, rng, playing());
    drawFrame(ctx, state, colors);
    if (playing() || !isIdle(state)) start();
  };

  const start = () => {
    if (pending === null && ctx) pending = schedule(frame);
  };

  return {
    name: 'spectrum',
    run(display) {
      const dpr = globalThis.devicePixelRatio || 1;
      canvas = document.createElement('canvas');
      canvas.className = SPECTRUM_CLASS;
      // Decorative: nothing in it is worth announcing.
      canvas.setAttribute('aria-hidden', 'true');
      canvas.width = CANVAS_W * dpr;
      canvas.height = CANVAS_H * dpr;
      ctx = canvas.getContext('2d');
      if (!ctx) {
        console.warn(`${LOG_PREFIX} spectrum: no 2d context, giving up`);
        canvas = null;
        return;
      }
      ctx.scale(dpr, dpr);
      display.append(canvas);
      colors = readColors(canvas);
      state = createState();
      player().addEventListener('onplaypause', start);
      if (typeof ResizeObserver !== 'undefined') {
        resize = new ResizeObserver(() => {
          if (canvas) canvas.hidden = display.clientWidth < MIN_DISPLAY_W;
        });
        resize.observe(display);
      }
      start();
    },
    cleanup() {
      if (pending !== null) cancel(pending);
      pending = null;
      resize?.disconnect();
      resize = null;
      try {
        player().removeEventListener('onplaypause', start);
      } catch (err) {
        console.warn(`${LOG_PREFIX} spectrum: could not remove the onplaypause listener`, err);
      }
      canvas?.remove();
      canvas = null;
      ctx = null;
      colors = null;
    },
  };
}

// --- index.js ---
// @ts-check
// Entry point of the theme extension. After `pnpm build` this becomes the
// tail of theme.js, which Spicetify injects when inject_theme_js is on.
// Later issues push their injection into INJECTIONS here; the order is the
// order they mount in.

/** @type {import('./dom.js').Injection[]} */
const INJECTIONS = [createMarqueeInjection(), createSpectrumInjection()];

async function main() {
  try {
    await waitForSpicetify();
  } catch (err) {
    console.error(`${LOG_PREFIX} ${err instanceof Error ? err.message : err}`);
    return;
  }
  mount(INJECTIONS);
  console.log(`${LOG_PREFIX} mounted`);
}

main();
})();
