// @ts-check
// Concatenates the ES modules in src/ into the single theme.js that
// Spicetify loads. No bundler: imports are dropped and exports unwrapped,
// so every module shares one IIFE scope.
//
// Source conventions this relies on: one `import` per line (no multi-line
// import lists) and named exports only (no `export default`).
import { existsSync } from 'node:fs';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { isMain, repoRoot } from './lib/main.js';

// Fixed order so a module only depends on the ones listed before it.
// Files that do not exist yet are skipped; unknown files are an error.
export const ORDER = ['time.js', 'marquee.js', 'spectrum.js', 'dom.js', 'index.js'];

const HEADER = '// generated by scripts/build.js, do not edit\n';

const IMPORT_LINE = /^\s*import\s[^;]*;?\s*$/;
const EXPORT_PREFIX = /^(\s*)export\s+/;

/**
 * Removes `import` lines and the `export` keyword from a module source.
 * @param {string} source
 * @returns {string}
 */
export function stripModuleSyntax(source) {
  return source
    .split('\n')
    .filter((line) => !IMPORT_LINE.test(line))
    .map((line) => line.replace(EXPORT_PREFIX, '$1'))
    .join('\n');
}

/**
 * @param {{ srcDir: string, outFile: string }} options
 * @returns {Promise<string>} the generated file content
 */
export async function build({ srcDir, outFile }) {
  const present = (await readdir(srcDir)).filter((name) => name.endsWith('.js'));
  const unknown = present.filter((name) => !ORDER.includes(name));
  if (unknown.length > 0) {
    throw new Error(`src/ has files missing from ORDER in scripts/build.js: ${unknown.join(', ')}`);
  }

  const parts = [];
  for (const name of ORDER) {
    const file = path.join(srcDir, name);
    if (!existsSync(file)) continue;
    const source = await readFile(file, 'utf8');
    parts.push(`// --- ${name} ---\n${stripModuleSyntax(source).trim()}`);
  }

  const output = `${HEADER}(function () {\n'use strict';\n\n${parts.join('\n\n')}\n})();\n`;
  await writeFile(outFile, output);
  return output;
}

if (isMain(import.meta.url)) {
  const root = repoRoot(import.meta.url);
  await build({ srcDir: path.join(root, 'src'), outFile: path.join(root, 'theme.js') });
}
